#!/bin/bash

# Install Camelot
pip3 install "camelot-py[base]"

# Install PyPDF2
pip3 install PyPDF2<3.0

xcode-select --install

curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh

# Add a success message at the end of the script
echo "Installation completed successfully"

# Add an error message if the installation fails
if [ $? -ne 0 ]; then
    echo "Installation failed"
fi
